### ISSUE TITLE
Ensure that collector url is in expected format

### ISSUE THREAD

**Issue by Dan1ve** [cqse/teamscale-javascript-profiler#9]
Following [the documentation](https://docs.teamscale.com/howto/recording-test-coverage-for-javascript/#dump-interval), we ran the instrumenter but passed a url starting with `http://` as `--collector` option:

```
npx @teamscale/javascript-instrumenter \
    test/casestudies/angular-hero-app/dist/ \
    --collector http://foo.bar:1234 \
    --in-place \
    --include-origin src/app/**/*
```

This results in `NaN` being set as url in the instrumented scripts.

IMHO we should either simply remove `http(s)://` prefixes (preferred) or throw an error in case an unexpected url is passed.

**Comment by stahlbauer** [comment]
Thanks for the bug report. We will process this ticket with the internal number `TS-30083`. Closing this report on GH.
